export * from './lib/teacher/teacher.component';
export * from './lib/teacher/teacher-account.component';
export * from './lib/teacher/teacher-favorites.component';
export * from './lib/teacher/teacher-history.component';
export * from './lib/teacher/teacher-playlist.component';
export * from './lib/teacher/teacher-courses.component';
export * from './lib/teacher/teacher-course-detail.component';
export * from './lib/teacher/teacher-course-edit.component';
export * from './lib/teacher/teacher.routes';
